// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/337587de8c13868283993bfacdcdd1a0f3291e7f/escape-html/index.d.ts
declare module 'escape-html' {
// Type definitions for escape-html
// Project: https://github.com/component/escape-html
// Definitions by: Elisée MAURER <https://github.com/elisee/>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped


function escapeHTML(text: string): string;
namespace escapeHTML { }

export = escapeHTML;
}
